# Generated by Django 3.0 on 2022-06-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('color_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['color_id'],
            },
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('boots_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('countries', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='armen_app.Colors')),
            ],
            options={
                'ordering': ['boots_id'],
            },
        ),
    ]
